###
GET http://localhost:3000/task/all
Accept: application/json

###
POST http://localhost:3000/task
Content-Type: application/json
{
  "title": ""
}

###
PATCH localhost:3000/task/2
Content-Type: application/json
{
  "title": "PATCH TASK22"
}

###
DELETE localhost:3000/task/2



### USERS
GET http://localhost:3000/task/all
Accept: application/json

###
POST http://localhost:3000/task
Content-Type: application/json
{
  "title": ""
}

###
PATCH localhost:3000/task/2
Content-Type: application/json
{
  "title": "PATCH TASK22"
}

###
DELETE localhost:3000/task/2



###
POST localhost:3000/users
Content-Type: application/json

{
  "last_name": "Штин",
  "first_name": "Роман",
  "email": "romanstin001@gmail.com",
  "login": "roma4444",
  "password": "Roma4444_",
  "role": "admin"
}

###
DELETE localhost:3000/users/3

###
PATCH localhost:3000/users/4
Content-Type: application/json

{
  "deleted_at": "2025-07-12 19:33:03.591934"
}



###
POST localhost:3000/audit_history
Content-Type: application/json

{
  "object_type": "test",
  "object_id": 1,
  "old_value":  "123",
  "new_value":  "321",
  "source_info":  "schpion",
  "user_id": 4
}


###
POST localhost:3000/employees
Content-Type: application/json

{
  "last_name": "Штин",
  "first_name": "Роман",
  "middle_name": "Валерьевич"
}

###
GET localhost:3000/employees/f


###
POST localhost:3000/passport-info
Content-Type: application/json

{
  "passport_data": "{\"seria\": 1234, \"nomer\": 123456}",
  "employee_id": 1
}

###
POST http://localhost:3000/files
Content-Type: application/json

{
  "filename": "test",
  "download_path": "locale/file",
  "file_size": 123,
  "employee_id": 1
}

###
POST http://localhost:3000/organizations
Content-Type: application/json

{
  "name": "tes",
  "comment": "top org",
  "file_size": 123,
  "employee_id": 1
}

###
POST http://localhost:3000/departments
Content-Type: application/json

{
"name": "test",
"comment": "top department",
"organization_id": 2
}

###
POST http://localhost:3000/recruit-opers
Content-Type: application/json

{
  "salary": 100,
  "employee_id": 2,
  "department_id": 1,
  "position_id": 1
}